// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inputprop.proto

package edu.umich.imlc.collabrify.collabrify_dummy_app;

public final class InputProp {
  private InputProp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PropertiesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string typedText = 1;
    /**
     * <code>required string typedText = 1;</code>
     */
    boolean hasTypedText();
    /**
     * <code>required string typedText = 1;</code>
     */
    java.lang.String getTypedText();
    /**
     * <code>required string typedText = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypedTextBytes();

    // required .collabrify_dummy_app.Properties.EditMode mode = 2;
    /**
     * <code>required .collabrify_dummy_app.Properties.EditMode mode = 2;</code>
     */
    boolean hasMode();
    /**
     * <code>required .collabrify_dummy_app.Properties.EditMode mode = 2;</code>
     */
    edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.EditMode getMode();

    // required int32 cursorPosition = 3;
    /**
     * <code>required int32 cursorPosition = 3;</code>
     */
    boolean hasCursorPosition();
    /**
     * <code>required int32 cursorPosition = 3;</code>
     */
    int getCursorPosition();

    // required string userName = 4;
    /**
     * <code>required string userName = 4;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 4;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>required string userName = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();
  }
  /**
   * Protobuf type {@code collabrify_dummy_app.Properties}
   */
  public static final class Properties extends
      com.google.protobuf.GeneratedMessage
      implements PropertiesOrBuilder {
    // Use Properties.newBuilder() to construct.
    private Properties(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Properties(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Properties defaultInstance;
    public static Properties getDefaultInstance() {
      return defaultInstance;
    }

    public Properties getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Properties(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              typedText_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.EditMode value = edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.EditMode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                mode_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              cursorPosition_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              userName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.internal_static_collabrify_dummy_app_Properties_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.internal_static_collabrify_dummy_app_Properties_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.class, edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.Builder.class);
    }

    public static com.google.protobuf.Parser<Properties> PARSER =
        new com.google.protobuf.AbstractParser<Properties>() {
      public Properties parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Properties(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Properties> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code collabrify_dummy_app.Properties.EditMode}
     */
    public enum EditMode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INSERT = 0;</code>
       */
      INSERT(0, 0),
      /**
       * <code>DELETE = 1;</code>
       */
      DELETE(1, 1),
      ;

      /**
       * <code>INSERT = 0;</code>
       */
      public static final int INSERT_VALUE = 0;
      /**
       * <code>DELETE = 1;</code>
       */
      public static final int DELETE_VALUE = 1;


      public final int getNumber() { return value; }

      public static EditMode valueOf(int value) {
        switch (value) {
          case 0: return INSERT;
          case 1: return DELETE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EditMode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EditMode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EditMode>() {
              public EditMode findValueByNumber(int number) {
                return EditMode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.getDescriptor().getEnumTypes().get(0);
      }

      private static final EditMode[] VALUES = values();

      public static EditMode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EditMode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:collabrify_dummy_app.Properties.EditMode)
    }

    private int bitField0_;
    // required string typedText = 1;
    public static final int TYPEDTEXT_FIELD_NUMBER = 1;
    private java.lang.Object typedText_;
    /**
     * <code>required string typedText = 1;</code>
     */
    public boolean hasTypedText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string typedText = 1;</code>
     */
    public java.lang.String getTypedText() {
      java.lang.Object ref = typedText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          typedText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string typedText = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypedTextBytes() {
      java.lang.Object ref = typedText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typedText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .collabrify_dummy_app.Properties.EditMode mode = 2;
    public static final int MODE_FIELD_NUMBER = 2;
    private edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.EditMode mode_;
    /**
     * <code>required .collabrify_dummy_app.Properties.EditMode mode = 2;</code>
     */
    public boolean hasMode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .collabrify_dummy_app.Properties.EditMode mode = 2;</code>
     */
    public edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.EditMode getMode() {
      return mode_;
    }

    // required int32 cursorPosition = 3;
    public static final int CURSORPOSITION_FIELD_NUMBER = 3;
    private int cursorPosition_;
    /**
     * <code>required int32 cursorPosition = 3;</code>
     */
    public boolean hasCursorPosition() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 cursorPosition = 3;</code>
     */
    public int getCursorPosition() {
      return cursorPosition_;
    }

    // required string userName = 4;
    public static final int USERNAME_FIELD_NUMBER = 4;
    private java.lang.Object userName_;
    /**
     * <code>required string userName = 4;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string userName = 4;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      typedText_ = "";
      mode_ = edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.EditMode.INSERT;
      cursorPosition_ = 0;
      userName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTypedText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCursorPosition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypedTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, mode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, cursorPosition_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUserNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypedTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, mode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cursorPosition_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUserNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code collabrify_dummy_app.Properties}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.PropertiesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.internal_static_collabrify_dummy_app_Properties_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.internal_static_collabrify_dummy_app_Properties_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.class, edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.Builder.class);
      }

      // Construct using edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        typedText_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        mode_ = edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.EditMode.INSERT;
        bitField0_ = (bitField0_ & ~0x00000002);
        cursorPosition_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.internal_static_collabrify_dummy_app_Properties_descriptor;
      }

      public edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties getDefaultInstanceForType() {
        return edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.getDefaultInstance();
      }

      public edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties build() {
        edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties buildPartial() {
        edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties result = new edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.typedText_ = typedText_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mode_ = mode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cursorPosition_ = cursorPosition_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.userName_ = userName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties) {
          return mergeFrom((edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties other) {
        if (other == edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.getDefaultInstance()) return this;
        if (other.hasTypedText()) {
          bitField0_ |= 0x00000001;
          typedText_ = other.typedText_;
          onChanged();
        }
        if (other.hasMode()) {
          setMode(other.getMode());
        }
        if (other.hasCursorPosition()) {
          setCursorPosition(other.getCursorPosition());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000008;
          userName_ = other.userName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTypedText()) {
          
          return false;
        }
        if (!hasMode()) {
          
          return false;
        }
        if (!hasCursorPosition()) {
          
          return false;
        }
        if (!hasUserName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string typedText = 1;
      private java.lang.Object typedText_ = "";
      /**
       * <code>required string typedText = 1;</code>
       */
      public boolean hasTypedText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string typedText = 1;</code>
       */
      public java.lang.String getTypedText() {
        java.lang.Object ref = typedText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          typedText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string typedText = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypedTextBytes() {
        java.lang.Object ref = typedText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          typedText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string typedText = 1;</code>
       */
      public Builder setTypedText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        typedText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string typedText = 1;</code>
       */
      public Builder clearTypedText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        typedText_ = getDefaultInstance().getTypedText();
        onChanged();
        return this;
      }
      /**
       * <code>required string typedText = 1;</code>
       */
      public Builder setTypedTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        typedText_ = value;
        onChanged();
        return this;
      }

      // required .collabrify_dummy_app.Properties.EditMode mode = 2;
      private edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.EditMode mode_ = edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.EditMode.INSERT;
      /**
       * <code>required .collabrify_dummy_app.Properties.EditMode mode = 2;</code>
       */
      public boolean hasMode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .collabrify_dummy_app.Properties.EditMode mode = 2;</code>
       */
      public edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.EditMode getMode() {
        return mode_;
      }
      /**
       * <code>required .collabrify_dummy_app.Properties.EditMode mode = 2;</code>
       */
      public Builder setMode(edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.EditMode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        mode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .collabrify_dummy_app.Properties.EditMode mode = 2;</code>
       */
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mode_ = edu.umich.imlc.collabrify.collabrify_dummy_app.InputProp.Properties.EditMode.INSERT;
        onChanged();
        return this;
      }

      // required int32 cursorPosition = 3;
      private int cursorPosition_ ;
      /**
       * <code>required int32 cursorPosition = 3;</code>
       */
      public boolean hasCursorPosition() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 cursorPosition = 3;</code>
       */
      public int getCursorPosition() {
        return cursorPosition_;
      }
      /**
       * <code>required int32 cursorPosition = 3;</code>
       */
      public Builder setCursorPosition(int value) {
        bitField0_ |= 0x00000004;
        cursorPosition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cursorPosition = 3;</code>
       */
      public Builder clearCursorPosition() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cursorPosition_ = 0;
        onChanged();
        return this;
      }

      // required string userName = 4;
      private java.lang.Object userName_ = "";
      /**
       * <code>required string userName = 4;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string userName = 4;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 4;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 4;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 4;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        userName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:collabrify_dummy_app.Properties)
    }

    static {
      defaultInstance = new Properties(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:collabrify_dummy_app.Properties)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_collabrify_dummy_app_Properties_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_collabrify_dummy_app_Properties_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017inputprop.proto\022\024collabrify_dummy_app\"" +
      "\246\001\n\nProperties\022\021\n\ttypedText\030\001 \002(\t\0227\n\004mod" +
      "e\030\002 \002(\0162).collabrify_dummy_app.Propertie" +
      "s.EditMode\022\026\n\016cursorPosition\030\003 \002(\005\022\020\n\010us" +
      "erName\030\004 \002(\t\"\"\n\010EditMode\022\n\n\006INSERT\020\000\022\n\n\006" +
      "DELETE\020\001B;\n.edu.umich.imlc.collabrify.co" +
      "llabrify_dummy_appB\tInputProp"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_collabrify_dummy_app_Properties_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_collabrify_dummy_app_Properties_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_collabrify_dummy_app_Properties_descriptor,
              new java.lang.String[] { "TypedText", "Mode", "CursorPosition", "UserName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
